### ISSUE TITLE
roslaunch orb_slam2_dense tum_pioneer.launch    

### ISSUE THREAD

**Issue by molong-d** [ZhouJankin/MultiMap3D#1]
Hello author, thank you for your excellent work. I hope to reproduce your work, but I have encountered a problem: when I run rosluanch, I can finally see rviz but no map or image is displayed.
But when I run ORB-SLAM2_DENSE that you previously used, I am able to create a map. May I ask if you can help me see where the problem is?

1）This is the naming convention for Python

(multimap3d) l@pc:~/slam/vslam/multiMap3D$ python src/MultiMap3D/ORB-SLAM2_DENSE-master/Examples/ROS/ORB_SLAM2_DENSE/scripts/fcaf3d_sort_demo.py
@@@@@/home/l/slam/vslam/multiMap3D/src/MultiMap3D/ORB-SLAM2_DENSE-master/Examples/ROS/ORB_SLAM2_DENSE/scripts/room_classifier/features_for_each_label_FEATURES_18.pkl
Accuracy =  0.81
/home/l/anaconda3/envs/multimap3d/lib/python3.8/site-packages/MinkowskiEngine/__init__.py:221: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
  warnings.warn(
Loads checkpoint by local backend from path: /home/l/slam/vslam/multiMap3D/src/MultiMap3D/checkpoints/fcaf3d_8x2_scannet-3d-18class_20220805_084956.pth
start

2）
2-1)
tum_pioneer.launch
 <arg name="setting_path" doc="Path of SLAM and camera config .yaml file"
         default="/home/l/slam/vslam/multiMap3D/src/MultiMap3D/ORB-SLAM2_DENSE-master/Examples/ROS/ORB_SLAM2_DENSE/params/TUM3.yaml" />
    <arg name="dataset_path" doc="Path of rosbag dataset, if `use_sim is enabled`"
         default="/home/l/slam/data/rgbd_dataset_freiburg3_long_office_household.bag" />

2-2）
rgbd_launch.launch
    <arg name="voc_path" doc="Path of DBoW dictionary"
         default="/home/l/slam/vslam/multiMap3D/src/MultiMap3D/ORB-SLAM2_DENSE-master/Vocabulary/ORBvoc.bin" />
    <arg name="setting_path" doc="Path of SLAM and camera config .yaml file"
         default="/home/l/slam/vslam/multiMap3D/src/MultiMap3D/ORB-SLAM2_DENSE-master/Examples/ROS/ORB_SLAM2_DENSE/params/TUM3.yaml" />

3）These are some running images
![2023-12-14 14-51-21 的屏幕截图](https://github.com/ZhouJankin/MultiMap3D/assets/44089363/50988dd5-3e93-48fd-b5cf-c04eba25306f)

![2023-12-14 14-56-34 的屏幕截图](https://github.com/ZhouJankin/MultiMap3D/assets/44089363/eeefa700-4357-471a-a766-2d7557288ef0)
![2023-12-14 14-59-16 的屏幕截图](https://github.com/ZhouJankin/MultiMap3D/assets/44089363/6f6f84c3-a5c8-4e0b-a158-16a46790b5f7)
![2023-12-14 14-59-23 的屏幕截图](https://github.com/ZhouJankin/MultiMap3D/assets/44089363/1d7d2367-f192-429e-a742-fa5d6bd4a16d)
![2023-12-14 14-59-30 的屏幕截图](https://github.com/ZhouJankin/MultiMap3D/assets/44089363/0c3b05b8-f453-43f9-9c04-f92494b87c52)

**Comment by molong-d** [comment]
I solved it, it's a rostopic issue

**Comment by ZhouJankin** [comment]
Cool, Mate.
Also I found that you used CPU_ONLY version for Minkowski Engine. I'm not sure if it will work or not.
